CREATE TABLE IF NOT EXISTS Chat (
	IDChat 			SERIAL NOT NULL PRIMARY KEY CHECK (IDChat >= 0),
	Nome			VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Usuario (
	IDUsuario		SERIAL PRIMARY KEY CHECK (IDUsuario >= 0),
	Nome			VARCHAR(100) NOT NULL,
	Foto			BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS Chat_tem_Usuario (
	IDChat_FK		SERIAL NOT NULL REFERENCES Chat(IDChat),
	IDUsuario_FK	SERIAL NOT NULL REFERENCES Usuario(IDUsuario),
	PRIMARY KEY(IDChat_FK, IDUsuario_FK)
);

CREATE TABLE IF NOT EXISTS Mensagem (
	IDMsg			SERIAL NOT NULL PRIMARY KEY,
	Hr_env			TIMESTAMP NOT NULL,
	Msg				VARCHAR(500),
	ChatID			SERIAL NOT NULL REFERENCES Chat(IDChat),
	IDUsuario		SERIAL NOT NULL REFERENCES Usuario(IDUsuario)
);
